add the auto_rescale_y on the GraphVisual model and make the depth of grid on GridVisual not relative to pixel width
ABRG-Models/morphologica pull request #235
Opened 2024-10-03 18:16 UTC by fabien-colonnier

Add the option to have rescale x in the append and in the update function.
It has been tested when both x and y are updated simultaneously. In update, it is not supporting 2 y axis yet. Not test was made to check it

2024-10-04 09:06 UTC, optseb requested changes
Just a fix required for the graph example, either to reset it back to x^3 or change the labels to say that dataset 1 is a graph of y = x

2024-10-04 09:07 UTC, optseb commented
Oh, would it be a good idea and easy to throw an error if an update() was called with rescale_y  set true to avoid unexpected behaviour?

2024-10-04 15:08 UTC, fabien-colonnier commented on examples/graph_incoming_data_rescale.cpp
> +        morph::vvec<float> data = 2.1f * absc.pow(1);
I corrected, I forgot to revert what I modify to validate it was working

2024-10-04 17:12 UTC, fabien-colonnier commented
I tested and corrected to have the full support of auto_rescale in the update function and added the auto_rescale_fit to fit the y axis. It is more complicated in the x axis as it is shared for different curves.

2024-10-04 17:14 UTC, fabien-colonnier commented
As I am writing this, I realize the auto_rescale_fit function doesn't handle multiple curves on one y axis. It will resize the axis according to the last dataset to be updated...

2024-10-04 17:19 UTC, fabien-colonnier commented
I added a comment for now, as It means rechecking all the datasets or storing the min and max for each one... which is tedious...

2024-10-05 10:51 UTC, sebjameswml commented
All looks good now.

2024-10-05 10:51 UTC, merged